# Generated by Django 3.1 on 2020-09-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servicio',
        ),
    ]
